// ui-svelte/src/App.svelte
<script lang="ts">
    import { onDestroy, onMount, setContext } from "svelte";
    import { writable } from "svelte/store";
    import Chat from "./components/Chat.svelte";
    import Chats from "./components/Chats.svelte";
    import Login from "./components/Login.svelte";
    import SideBar from "./components/SideBar.svelte";
    import { chatSelected, Token } from "./stores";

    $: token = $Token;
    $: isAuth = !!token;

    let websocket = writable(
        new WebSocket(
            `ws://localhost:8000/ws/?token=${
                localStorage.getItem("token") || ""
            }`
        )
    );

    const unSubToken = Token.subscribe((token) => {
        console.log("App sub token", token, $websocket.readyState);
        if ($websocket.readyState === WebSocket.OPEN) $websocket.close();
        websocket.set(
            new WebSocket(`ws://localhost:8000/ws/?token=${token || ""}`)
        );
    });

    setContext("websocket", websocket);
    onDestroy(() => unSubToken());
</script>

<main>
    <button on:click={() => Token.signout()}>Logout</button>
    <SideBar>
        <Chats />
    </SideBar>
    <div class="pl-64">
        {#if isAuth}
            {#if $chatSelected}
                <Chat />
            {:else}
                <div
                    class="h-[95vh] flex justify-center text-4xl text-slate-600"
                >
                    Seleccione un chat
                </div>
            {/if}
        {:else}
            <Login />
        {/if}
    </div>
</main>

<style lang="postcss" global>
    @tailwind base;
    @tailwind components;
    @tailwind utilities;
</style>

// ui/src/App.vue
<script setup lang="ts">
import {token, chatSelected} from "./stores"
import Login from "./components/Login.vue"
import SideBar from "./components/SideBar.vue"
import Chats from "./components/Chats.vue"
import Chat from './components/Chat.vue'

</script>

<template>
    <div>
        <side-bar>
            <chats />
        </side-bar>
        <div class="pl-64" v-if="token">
            <chat v-if="chatSelected" />
            <div
                v-else
                class="h-[95vh] flex justify-center text-4xl text-slate-600"
            >Seleccione un chat</div>
        </div>
        <div v-else class="pl-64">
            <login />
        </div>
    </div>
</template>
