// ui-svelte/src/components/Chat.svelte
<script lang="ts">
    import { onDestroy } from "svelte";

    import { chatSelected } from "../stores/chat";
    import { Token } from "../stores/token";
    import type { ChatDetail, MessageDetail, MessageList } from "../types";

    let input: string;
    let chat: ChatDetail;
    let next: string;
    let messages: MessageDetail[];
    let loading: boolean = false;
    const unChatSelected = chatSelected.subscribe(async (c) => {
        chat = c;
        loading = true;
        const response = await fetch(
            `http://localhost:8000/messages/?chat=${c.id}`,
            {
                method: "GET",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Token ${localStorage.getItem("token")}`,
                },
            }
        );
        const data: MessageList = await response.json();
        messages = [...data.results];
        next = data.next;
        loading = false;
    });

    const createMessage = async () => {
        await fetch(`http://localhost:8000/messages/`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                Authorization: `Token ${localStorage.getItem("token")}`,
            },
            body: JSON.stringify({
                text: input,
                chat: chat.id,
            }),
        });
    };

    let ws: WebSocket;

    const unToken = Token.subscribe((t) => {
        console.log("token changed", t);
        const token = localStorage.getItem("token");
        if (token) {
            ws = new WebSocket(`ws://localhost:8000/ws/chats/?token=${token}`);
            ws.onopen = () => {
                console.log("ws opened");
                ws.send(
                    JSON.stringify({
                        action: "subscribe_to_chat",
                        id: chat.id,
                        request_id: Math.random(),
                    })
                );
                console.log(chat.id);
            };
            ws.onmessage = (e) => {
                const data: MessageDetail = JSON.parse(e.data);
                console.log("ws message", data);
                messages = [...messages, data];
            };
        } else if (ws) {
            ws.close();
        }
    });

    onDestroy(() => {
        unToken();
        unChatSelected();
    });
    $: console.log(messages);
</script>

{#if !loading}
    <div class="h-[95vh] flex flex-col-reverse">
        <form class="flex" on:submit|preventDefault={(e) => createMessage()}>
            <input
                bind:value={input}
                type="text"
                class="bg-slate-200 rounded-md px-2 mr-2 grow"
            />
            <button
                type="submit"
                class="
                    px-10
                    rounded-md
                    bg-slate-700
                    text-white
                    hover:bg-slate-400 hover:text-black
                "
            >
                Send
            </button>
        </form>
        {#each messages as { id, created_at, text, created_by: { first_name, last_name, username, email } }}
            <div>
                {created_at} - {username}: {text}
            </div>
        {:else}
            No messages
        {/each}
    </div>
{:else}
    Loading...
{/if}

// ui/src/components/Chat.vue
<script lang="ts" setup>
    import { ref, onMounted, watch } from "vue";
    import { MessageDetail, MessageList } from "../types";
    import { useWs } from "../hooks/use-ws";

    const props = defineProps<{ id?: number }>();
    const loading = ref(false);
    const messages = ref<MessageDetail[]>([]);
    const input = ref("");
    const next = ref("");
    const { ws } = useWs();

    watch(
        () => props.id,
        (newId, oldId) => {
            ws.value.onmessage = (event) => {
                console.log(event);
                const data: MessageDetail = JSON.parse(event.data);
                console.log(data);
                messages.value.push(data);
            };
            console.log("watch", oldId, newId);
            if (newId) {
                if (ws.value.readyState !== WebSocket.OPEN) {
                    ws.value.onopen = () => {
                        if (oldId) {
                            ws.value.send(
                                JSON.stringify({
                                    action: "unsubscribe_to_chat",
                                    id: oldId,
                                    request_id: Math.random(),
                                })
                            );
                        }
                        ws.value.send(
                            JSON.stringify({
                                action: "subscribe_to_chat",
                                id: newId,
                                request_id: Math.random(),
                            })
                        );
                    };
                } else {
                    if (oldId) {
                        ws.value.send(
                            JSON.stringify({
                                action: "unsubscribe_to_chat",
                                id: oldId,
                                request_id: Math.random(),
                            })
                        );
                    }
                    ws.value.send(
                        JSON.stringify({
                            action: "subscribe_to_chat",
                            id: newId,
                            request_id: Math.random(),
                        })
                    );
                }
            }
        },
        { immediate: true }
    );

    const getMessages = async () => {
        loading.value = true;
        try {
            const response = await fetch(
                `http://localhost:8000/messages/?chat=${props.id}`,
                {
                    method: "GET",
                    headers: {
                        "Content-Type": "application/json",
                        Authorization: `Token ${localStorage.getItem("token")}`,
                    },
                }
            );
            const data: MessageList = await response.json();
            if (response.ok) {
                messages.value = [...data.results];
                next.value = data.next;
            }
        } finally {
            loading.value = false;
        }
    };

    getMessages();

    const createMessage = async () => {
        try {
            await fetch(`http://localhost:8000/messages/`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Token ${localStorage.getItem("token")}`,
                },
                body: JSON.stringify({
                    text: input.value,
                    chat: props.id,
                }),
            });
        } finally {
        }
    };
</script>

<template>
    <div class="h-screen bg-stone-100">
        <div class="min-h-full flex flex-col-reverse">
            <form @submit.prevent="createMessage" class="flex flex-row">
                <input
                    v-model="input"
                    type="text"
                    class="bg-slate-200 rounded-md px-2 mr-2 grow"
                />
                <button
                    type="submit"
                    class="
                        px-10
                        rounded-md
                        bg-slate-700
                        text-white
                        hover:bg-slate-400 hover:text-black
                    "
                >
                    Send
                </button>
            </form>
            <div
                v-for="message in messages"
                :key="message.id"
                class="
                    transition-transform
                    duration-1000
                    delay-1000
                    ease-in-out
                "
            >
                {{ message.text }}
            </div>
        </div>
    </div>
</template>
