// ui-svelte/src/components/Login.svelte
<script lang="ts">
    import { Token } from "../stores/token";

    let username: string;
    let password: string;
    let loading: boolean;

    const onSubmit = async () => {
        loading = true;
        const response = await fetch("http://localhost:8000/users/login/", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ username, password }),
        });
        const data = await response.json();
        const { token } = data;
        Token.signin(token);
        loading = false;
    };
</script>

<div class="h-screen flex items-center justify-center">
    <form on:submit|preventDefault={onSubmit} class="">
        <label for="username">Username</label>
        <input id="username" bind:value={username} type="text" />
        <label for="password">Password</label>
        <input id="password" bind:value={password} type="password" />
        <button type="submit">
            {#if loading}
                Login...
            {:else}
                Login
            {/if}
        </button>
    </form>
</div>

// ui/src/components/Login.vue
<script setup lang="ts">
    import { reactive, ref } from "vue";
    import { token } from "../stores";

    const form = reactive({
        username: "",
        password: "",
    });
    const loading = ref(false);
    const error = ref("");

    const onSubmit = async () => {
        loading.value = true;
        try {
            const response = await fetch("http://localhost:8000/users/login/", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(form),
            });
            const data = await response.json();
            if (response.ok) {
                localStorage.setItem("token", data.token);
                token.value = data.token;
            } else {
                console.error(data);
                throw new Error("Login failed");
            }
        } catch (error) {
            console.error(error);
        } finally {
            loading.value = false;
        }
    };
</script>

<template>
    <div class="flex justify-center h-screen align-middle">
        {{ error }}
        <form @submit.prevent="onSubmit" class="max-w-md flex-row">
            <h3 class="p-2 text-center">Login</h3>
            <div class="p-2">
                <label class="p-1">Username</label>
                <input
                    class="bg-slate-200 rounded-md p-2 w-full"
                    type="text"
                    v-model="form.username"
                />
            </div>
            <div class="p-2">
                <label class="p-1">Password</label>
                <input
                    class="bg-slate-200 rounded-md p-2 w-full"
                    type="password"
                    v-model="form.password"
                />
            </div>
            <div class="p-2">
                <button
                    class="
                        p-2
                        w-full
                        rounded-lg
                        bg-slate-700
                        text-white
                        hover:bg-slate-400 hover:text-black
                    "
                    type="submit"
                >
                    Login!
                </button>
            </div>
        </form>
    </div>
</template>
