// ui/src/components/Message.vue
<script lang="ts" setup>
import {MessageDetail} from '../types'
import {fromNow} from '../utils'


const {message: {created_at, created_by: {username} = {}, text}} = defineProps<{message: MessageDetail}>()
</script>

<template>
    <div>{{fromNow(created_at)}} - {{username}}: {{message.text}}</div>
</template>

// ui-svelte/src/components/messages/Message.svelte
<script lang="ts">
    import { fade } from "svelte/transition";
    import type { MessageDetail } from "../../types/index";
    import { fromNow } from "../../utils/index";
    export let message: MessageDetail;
</script>

<div transition:fade>
    {fromNow(message?.created_at)} - {message?.created_by?.username}: {message.text}
</div>
